yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('groups/', views.groups, name='groups'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/done/', views.feedback_done, name='feedback_done'),
    path('votepost/', views.votepost, name='votepost'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path('change/', PasswordChangeView.as_view(
         template_name="users/password_change_form.html"),
         name='change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
         template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('reset/', PasswordResetView.as_view(
         template_name="users/password_reset_form.html"),
         name='password_reset_form'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
         template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
         template_name="users/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
         template_name="users/password_reset_complete.html"),
         name='password_reset_complet'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found_view"

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

yatube/templates/includes/ajax_script.html
<script>
  $(document).ready(function () {
    $(".like").click(function() {
      var met = $( this );
      $.ajax({
        headers: {'X-CSRFToken': $.cookie('csrftoken')},
        type: 'POST',
        data: { post: $( this ).attr('id') },
        url: "{% url 'posts:votepost' %}",
        success: function (result) {
          if (result['status'] == 'add') {
            met.find('span').text(parseInt(met.find('span').text()) + 1);
          } else {
            met.find('span').text(parseInt(met.find('span').text()) - 1);
          }
        }
      });
    });
  });
</script>

yatube/templates/includes/footer.html
<small class="copyright">
  © {{ year }} Copyright
  <a href="/"><span style="color:red">Yatube</span></a>.
  Дизайн
  <a href="https://themes.3rdwavemedia.com" target="_blank">
    Xiaoying Riley
  </a>.
  <a href="{% url 'posts:feedback' %}">
    Обратная связь
  </a>.
</small>

yatube/templates/includes/header.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
<link id="theme-style" rel="stylesheet" href="{% static 'css/theme-51.css' %}">
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/jquery.cookie.js' %}"></script>

yatube/templates/includes/navigation.html
{% load static %}
  <h1 class="blog-name pt-lg-4 mb-0">
    <a class="no-text-decoration" href="{% url 'posts:index' %}">
      {% block title %}Yatube{% endblock %}
    </a>
  </h1>
  <nav class="navbar navbar-expand-lg navbar-dark" >
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navigation" class="collapse navbar-collapse flex-column" >
      <div class="profile-section pt-3 pt-lg-0">
        {% if user.is_authenticated %}
          <div class="bio mb-3">Привет, <a href="{% url 'posts:profile' user.username %}">{{ user.username|truncatechars:12 }}</a>!</div>
        {% endif %}
	      <hr>
      </div>
      <ul class="navbar-nav flex-column text-start">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:index' %}">Главная страница</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        <hr>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:change' %}">Сменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:signup' %}">Зарегистрироваться</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

yatube/templates/includes/paginator.html
{% if page_obj.paginator.num_pages > 1 %}
  <nav class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link " href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
      </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="?page={{ page.number }}">{{ page_obj.number }}</a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}