yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('groups/', views.groups, name='groups'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/done/', views.feedback_done, name='feedback_done'),
    path('votepost/', views.votepost, name='votepost'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path('change/', PasswordChangeView.as_view(
         template_name="users/password_change_form.html"),
         name='change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
         template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('reset/', PasswordResetView.as_view(
         template_name="users/password_reset_form.html"),
         name='password_reset_form'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
         template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
         template_name="users/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
         template_name="users/password_reset_complete.html"),
         name='password_reset_complet'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found_view"

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Имя группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Адрес для ЧПУ'
    )
    description = models.TextField(
        verbose_name='Описание группы'
    )

    class Meta:
        ordering = ('-title', )
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст сообщения',
        help_text='Старайтесь писать корректно'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    class Meta:
        ordering = ('-pub_date', )
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def __str__(self):
        return self.text[:25]


class VotePost(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Голос за этот пост',
        related_name='posts'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Проголосовавший'
    )

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')


class FeedBackForm(forms.Form):
    name = forms.CharField(max_length=40,
                           required=True,
                           label='Как вас величать?')
    email = forms.EmailField(required=True, label='E-Mail')
    text = forms.CharField(widget=forms.Textarea,
                           required=True,
                           label='Ваши слова',
                           help_text='И что таки ви хотите мне сказать?')

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from django.db.models import Count

from yatube.settings import (EMAIL_ADMIN, NUMBER_OF_POSTS,
                             NUMBER_OF_GROUP_PAGES)

from .forms import FeedBackForm, PostForm
from .models import Group, Post, User, VotePost


def page_not_found_view(request, exception):
    """Метод для вывода отдельной страницы c ошибкой."""
    return render(request, '404.html', status=404)


def index(request):
    """Вывод главной страницы + лайки"""
    posts = Post.objects.select_related('group', 'author').annotate(
        count=Count('posts'))
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Вывод списка записей от группы."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author').annotate(
        count=Count('posts'))
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj,
               'group': group, }
    return render(request, 'posts/group_list.html', context)


def groups(request):
    """Вывода списка групп."""
    groups = Group.objects.all()
    paginator = Paginator(groups, NUMBER_OF_GROUP_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/groups.html', context)


def profile(request, username):
    """Вывод страницы пользователя со списком сообщений"""
    user = get_object_or_404(User, username=username)
    posts = user.posts.select_related('author', 'group').annotate(
        count=Count('posts'))
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'username': user,
               'page_obj': page_obj, }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Вывод информации о сообщении"""
    post = get_object_or_404(Post.objects.select_related(
        'group', 'author').annotate(count=Count('posts')), pk=post_id)
    context = {'post': post, }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Создание нового сообщения: только для авторизированного пользователя"""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Редактирование сообщения: только для авторизированного пользователя и
    только для создателя данного сообщения."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author.pk != request.user.id:
        return redirect('posts:post_detail', post_id)

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'post_id': post_id,
               'form': form, }
    return render(request, 'posts/post_create.html', context)


def send_msg(email, name, text):
    """Метод отправки письма"""
    subject = "Вам оставили сообщение"
    body = f"""На вашем сайте, через форму обратной связи, было оставлено
    сообщение.

    {name} пишет:
    {text}

    """
    send_mail(
        subject, body, email, EMAIL_ADMIN,
    )


def feedback(request):
    """Куда на сайте без формы обратной связи то?"""
    form = FeedBackForm(request.POST)
    if form.is_valid():
        send_msg(form.cleaned_data['email'],
                 form.cleaned_data['name'],
                 form.cleaned_data['text'],)
        return redirect('posts:feedback_done')
    context = {'form': form, }
    return render(request, 'posts/feedback.html', context)


def feedback_done(request):
    return render(request, 'posts/feedback_done.html')


@login_required
def votepost(request):
    """Какая соц.сеть без лайков?"""
    if request.is_ajax():
        post = request.POST.get('post', None)
        vote = VotePost.objects.filter(
            user__id=request.user.id).filter(post=post)
        post = get_object_or_404(Post, pk=post)
        if not vote.exists():
            VotePost.objects.create(user=request.user, post=post)
            return JsonResponse({"status": 'add'}, status=200)
        else:
            vote.delete()
            return JsonResponse({"status": 'del'}, status=200)
    return render(request, "posts/votepost.html")

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/posts/feedback.html
{% extends 'base.html' %}
{% block title %}Обратная связь{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Обратная связь с администратором
        </div>
      <div class="card-body">

        <form method="post" action="">
          {% csrf_token %}
          {% load user_filters %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }} 
              {% if field.help_text %}
                <small 
                  id="{{ field.id_for_label }}-help"
                  class="form-text text-muted"
                >
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              Отправить
            </button>
          </div>
        </form>

      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/feedback_done.html
{% extends "base.html" %}
{% block title %}Письмо на деревню админушке отправлено{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Письмо на деревню админушке отправлено
        </div>
        <div class="card-body">
          <p>Ваше мнение очень важно для нас, потому мы обязательно с вами свяжемся… Но это не точно.</p>
          <p>Перейти на <a href="{% url 'posts:index' %}">главную страницу</a>.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  {% include 'includes/ajax_script.html' %}
  <section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
      <h1>{{ group.title }}</h1>
      <div class="intro">
        <p>{{ group.description|linebreaksbr }}</p>
      </div>
    </div>
  </section>
  <section class="blog-list px-3 py-5 p-md-5">
    {% if page_obj %}
      {% for post in page_obj %}
        {% include 'posts/includes/posts.html' %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %} 
      {% include 'includes/paginator.html' %}
    {% else %}
      <p>Вы попробовали открыть страницу не существующей или удалённой группы.</p>
    {% endif %}
  </section>
{% endblock %}

yatube/templates/posts/groups.html
{% extends 'base.html' %}
{% block title %}Список групп{% endblock %}
{% block content %}
  <section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
      <h1>Список групп</h1>
      <div class="intro">
      </div>
    </div>
  </section>
  <section class="blog-list px-3 py-5 p-md-5">
    <p>Всего групп: {{ page_obj.paginator.count }}</p>
    {% for group in page_obj %}
      <ul>
        <li>
          <a href="{% url 'posts:group_list' group.slug %}">{{ group.title }}</a>
        </li>
      </ul>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </section>
  {% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'includes/ajax_script.html' %}
  <section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
      <h2 class="heading" style="padding-top:1rem !important">Последние обновления на сайте</h2>
      <div class="intro"></div>
    </div>
  </section>
  <section class="blog-list px-3 py-5 p-md-5">
    {% for post in page_obj %}
      <article>
        {% include 'posts/includes/posts.html' %}
      <article>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </section>
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if post_id %}Редактировать запись{% else %}Добавить запись{% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if post_id %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
      <div class="card-body">

        <form method="post" action="
          {% if post_id %}
            {% url 'posts:post_edit' post_id %}
          {% else %}
            {% url 'posts:post_create' %}
          {% endif %}
        ">
          {% csrf_token %}
          {{ is_edit }}
          {% load user_filters %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }} 
              {% if field.help_text %}
                <small 
                  id="{{ field.id_for_label }}-help"
                  class="form-text text-muted"
                >
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if post_id %}Сохранить{% else %}Добавить{% endif %}  
            </button>
          </div>
        </form>

      </div>
    </div>
  </div>

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  {% include 'includes/ajax_script.html' %}
  <section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
      <h2 class="heading">{{ post.text|truncatechars:30 }}</h2>
      <div class="intro">
        Автор поста: {% include 'posts/includes/author.html' %}<br>
        Всего постов автора: {{ post.author.posts.count }}<br>
        {{ posts.user.pk }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </div>
    </div>
  </section>
    <article class="blog-post px-3 py-5 p-md-5">
    {% include 'posts/includes/posts.html' %}
    </article>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя
  {% if username.get_full_name %}
    {{ username.get_full_name  }}
  {% else %}
    {{ username.username }}
  {% endif %}
{% endblock %}
{% block content %}
  {% include 'includes/ajax_script.html' %}
  <section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
      <h2 class="heading" style="padding-top:1rem !important">
        Все посты пользователя
        {% if username.get_full_name %}
          {{ username.get_full_name  }}
        {% else %}
          {{ username.username }}
        {% endif %}
      </h2>
      <div class="intro">Всего постов:
        {{ username.posts.count }}
      </div>

    </div>
  </section>
  <article class="blog-post px-3 py-5 p-md-5">
      {% for post in page_obj %}
        {% include 'posts/includes/posts.html' %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %} 
  </article>

  <article class="blog-post px-3 py-5 p-md-5">
    {% include 'includes/paginator.html' %}
  </article>
{% endblock %}

yatube/templates/posts/user.html
{% extends 'base.html' %}
{% block title %}Информация о авторе {{ user.username }}{% endblock %} 
{% block content %}
  <h1>Информация о авторе 
    {% if user.get_full_name %}
      <a href="{% url 'posts:user_show' user.id %}">{{ user.get_full_name }}</a>
    {% else %}
      <a href="{% url 'posts:user_show' user.id %}">{{ user.username }}</a>
    {% endif %}
  </h1>
  <ul>
    <li>Дата регистрации: {{ user.date_joined|date:"d E Y" }}</li>
    {% if count > 0 %}
      <li>Оставил записей: {{ count }}</li>
    {% else %}
      <li>Пока не оставил ни одной записи</li>
    {% endif %}
  </ul>
{% endblock %} 